In [ ]:
import numpy as np
import torch
import pandas as pd
from torch.utils.data import DataLoader
import os, sys
sys.path.append(os.path.abspath('../models'))
from Dataset import ProteinCSVWindowDataset, ProteinEmbeddingWithLabelsDataset,  collate_fn_window
from models.original import OriginalModel, OriginalModelLarger
from models.small import SmallModel

CHECKPOINT_PATH = './checkpoints/original_bs8_lr3e-04_ep15_20250623_232208.pth'
TEST_DATA_PATH = r"E:\Data\embeddings41k\test\all_embeddings_and_labels.h5"
OUTPUT_CSV = 'predictions_emb_23.csv'
BATCH_SIZE = 32
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

# Modell und Testdaten laden
model = OriginalModel(input_size=1024, channels=512, num_classes=58)
model.load_state_dict(torch.load(CHECKPOINT_PATH, map_location=DEVICE))
model.to(DEVICE)
model.eval()

test_dataset = ProteinEmbeddingWithLabelsDataset(TEST_DATA_PATH)

test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False, collate_fn=collate_fn_window)

In [4]:
results = []

with torch.no_grad():
    for batch in test_loader:
        inputs = batch["embeddings"]
        targets = batch["labels"]
        inputs = inputs.to(DEVICE)
        outputs, _ = model(inputs)
        preds = outputs.argmax(dim=-1).cpu().numpy()
        targets = targets.cpu().numpy()
        break


In [ ]:
np.any(targets[0,:,:] != 0)

# reduce to 2D where every

In [ ]:

# show full target
np.set_printoptions(threshold=np.inf, linewidth=200)

targets[0,:,0]

In [32]:
indices = np.argwhere(targets != 0)
print(indices)

[[   0  105   47]
 [   0  106   47]
 [   0  107   47]
 [   0  108   47]
 [   0  109   47]
 [   0  110   47]
 [   0  111   47]
 [   0  112   47]
 [   0  113   47]
 [   0  114   47]
 [   0  115   47]
 [   0  116   47]
 [   0  117   47]
 [   0  118   47]
 [   0  119   47]
 [   0  120   47]
 [   0  121   47]
 [   0  122   47]
 [   0  123   47]
 [   0  124   47]
 [   0  125   47]
 [   0  126   47]
 [   0  127   47]
 [   0  128   47]
 [   0  129   47]
 [   0  130   47]
 [   0  131   47]
 [   0  132   47]
 [   0  133   47]
 [   0  134   47]
 [   0  135   47]
 [   0  136   47]
 [   0  137   47]
 [   0  138   47]
 [   0  139   47]
 [   0  140   47]
 [   0  141   47]
 [   0  142   47]
 [   0  143   47]
 [   0  144   47]
 [   0  145   47]
 [   0  146   47]
 [   0  147   47]
 [   0  148   47]
 [   0  149   47]
 [   0  150   47]
 [   0  151   47]
 [   0  152   47]
 [   0  153   47]
 [   0  154   47]
 [   0  155   47]
 [   0  156   47]
 [   0  157   47]
 [   0  158   47]
 [   0  159   47]
 [   0  16

In [34]:
mask = targets == 1
z_indices = np.argmax(mask, axis=2)
has_one = np.any(mask, axis=2)
new_targets = np.where(has_one, z_indices, 0)

In [35]:
new_targets

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
        47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47,
        47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0, 

In [36]:
new_targets.shape

(32, 1104)

In [8]:
preds.shape

(32, 1104)

In [45]:
new_targets[4]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 37, 37, 37, 37, 37, 37, 37,
       37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37,
       37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37,  0,  0,
     

In [44]:
preds[4]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 37, 37, 37, 37, 37, 37, 37,
       37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37,
       37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37,  0,  0,
     

In [46]:
import matplotlib.pyplot as plt
import os

os.makedirs('plots', exist_ok=True)

for x in range(new_targets.shape[0]):
    plt.figure(figsize=(12, 4))
    plt.plot(new_targets[x], label='Target', marker='o')
    plt.plot(preds[x], label='Prediction', marker='x')
    plt.title(f'Vergleich Target vs. Prediction für Sample {x}')
    plt.xlabel('Position (y)')
    plt.ylabel('Klassenindex (z)')
    plt.legend()
    plt.tight_layout()
    plt.savefig(f'plots/vergleich_{x}.png')
    plt.close()

In [47]:
import matplotlib.pyplot as plt
import numpy as np
import os

os.makedirs('plots', exist_ok=True)

num_classes = max(new_targets.max(), preds.max()) + 1

for x in range(new_targets.shape[0]):
    plt.figure(figsize=(12, 4))
    for arr, name in [(new_targets, 'Target'), (preds, 'Prediction')]:
        for cls in range(1, num_classes):  # Klasse 0 wird ausgelassen
            mask = (arr[x] == cls).astype(int)
            plt.plot(mask, label=f'{name} Klasse {cls}')
    plt.title(f'Klassen-Visualisierung für Sample {x}')
    plt.xlabel('Position (y)')
    plt.ylabel('Klassen-Präsenz')
    plt.legend()
    plt.tight_layout()
    plt.savefig(f'plots/klassen_visualisierung_{x}.png')
    plt.close()

C:\Users\danei\AppData\Local\Temp\ipykernel_20388\4102770174.py:19: UserWarning: Tight layout not applied. The bottom and top margins cannot be made large enough to accommodate all Axes decorations.
  plt.tight_layout()
